language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"

before_install:
  - cd src/server
  - mv config/storage-test.json config/storage.json
  - cp config/default-example.json config/default.json
